config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'boards#index'

  get '/boards/:id', to: 'boards#show', as: :boards_show

  get '/boards/:id/topics/new', to: 'board_topics#new', as: :board_topics_new
  post '/boards/:id/topics/new', to: 'board_topics#create', as: :board_topics_create

  get '/boards/:board_id/:id', to: 'board_topics#show', as: :board_topics_show

  get '/board/topics/:id/posts', to: 'board_topic_posts#list', as: :board_topic_posts_list
  post '/board/topics/:id/comment', to: 'board_topic_posts#comment', as: :board_topic_post_comment
  delete '/posts/:id', to: 'board_topic_posts#delete', as: :board_topic_posts_delete
  delete '/posts/:id/file', to: 'board_topic_posts#delete_file', as: :board_topic_posts_delete_file

  get '/user/new', to: 'users#new', as: :users_new
  post '/user/new', to: 'users#create', as: :users_create
  post '/user/logout', to: 'users#logout', as: :users_logout
  get '/user/login', to: 'users#login', as: :users_login
  post '/user/login', to: 'users#login_perform', as: :users_login_perform
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :board, optional: true
  has_many :boards
  has_many :board_topics, dependent: :destroy

  def to_param
    "#{id}-#{name.parameterize}"
  end
end

app/models/board_topic.rb
class BoardTopic < ApplicationRecord
  belongs_to :board
  belongs_to :user, optional: true

  has_many :board_topic_posts, dependent: :destroy

  validates :username, presence: true
  validates :title, presence: true

  def to_param
    "#{id}-#{title.parameterize}"
  end
end

app/models/board_topic_post.rb
class BoardTopicPost < ApplicationRecord
  belongs_to :board_topic
  belongs_to :user, optional: true

  has_one_attached :file

  validates :username, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: {case_sensitive: false}
  validates :email, presence: true, uniqueness: true, format: {with: URI::MailTo::EMAIL_REGEXP}
  has_many :board_topics, dependent: :nullify
  has_many :board_topic_posts, dependent: :nullify
  has_secure_password

  def self.current=(user)
    Thread.current[:user] = user if user.is_a?(User) || user.nil?
  end

  def self.current
    # Return is optional here and all functions use the last value as their return value
    return Thread.current[:user]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  before_action :identify_user

  def pundit_user
    User.current
  end

  private

  def identify_user
    user_data = cookies.encrypted[:forum_account]
    if user_data
      user_data = JSON.parse user_data
      if Date.parse(user_data['lifetime']) > Time.now
        User.current = User.find_by(id: user_data['user_id'])
        return
      end
    end
    User.current = nil
  end
end

app/controllers/board_topic_posts_controller.rb
class BoardTopicPostsController < ApplicationController

  # POST /boards/topics/:id/comment
  def comment
    authorize BoardTopicPost
    user = User.current
    post = BoardTopicPost.new(
        board_topic: BoardTopic.find(params[:id]),
        username: user.username,
        content: params[:board_topic_post][:content],
        user: user
    )
    post.file.attach params[:board_topic_post][:file]
    if post.save
      notify_on_post_update post
      flash[:success] = "Posted!"
    else
      flash[:error] = post.errors.full_messages.to_sentence
    end
    redirect_to board_topics_show_path(post.board_topic.board, post.board_topic)
  end

  # DELETE /posts/:id
  def delete
    post = BoardTopicPost.find(params[:id])
    authorize post
    post.destroy!
    notify_on_post_update post
    redirect_back fallback_location: root_path
  end

  # DELETE /posts/:id/file
  def delete_file
    post = BoardTopicPost.find(params[:id])
    authorize post

    post.file.purge
    notify_on_post_update post

    flash[:success] = 'file deleted'
    redirect_back fallback_location: root_path
  end

  # GET /board/topics/:id/posts
  def list
    @board_topic = BoardTopic.find(params[:id])
    @posts = @board_topic.board_topic_posts

    render layout: false
  end

  private

  def notify_on_post_update(post)
    BoardTopicNotificationsChannel.broadcast_to(
        post.board_topic,
        { event: 'post_updated', query_path: board_topic_posts_list_path(post.board_topic)}
    )
  end
end

app/controllers/board_topics_controller.rb
class BoardTopicsController < ApplicationController
  # GET /boards/:id/topics/new
  def new
    authorize BoardTopic
    Board.find(params[:id])
    @board_topic = BoardTopic.new
    @board_topic_post = BoardTopicPost.new
  end

  # POST /boards/:id/topics/create
  def create
    authorize BoardTopic
    user = User.current
    board = Board.find(params[:id])
    ApplicationRecord.transaction do
      @board_topic = BoardTopic.new(
          board: board,
          title: params[:board_topic][:title],
          username: user.username,
          user: user
      )
      @board_topic_post = BoardTopicPost.new(
          username: user.username,
          content: params[:board_topic][:board_topic_post][:content],
          user: user
      )
      if @board_topic.save
        @board_topic_post.board_topic = @board_topic
        if @board_topic_post.save
          notify_on_post_update @board_topic_post
          @board_topic = BoardTopic.new
          @board_topic_post = BoardTopicPost.new
          flash.now[:ok] = 'saved'
        else
          flash.now[:error] = @board_topic_post.errors.full_messages.to_sentence
          raise ActiveRecord::Rollback
        end
      else
        flash[:error] = @board_topic.errors.full_messages.to_sentence
      end
    end
    render :new
  end

  # GET /boards/:board_id/:id/
  def show
    @board_topic = BoardTopic.find(params[:id])
    @board_topic_post_answer = BoardTopicPost.new
    if @board_topic.to_param != params[:id] || @board_topic.board.to_param != params[:board_id]
      redirect_to board_topics_show_path(@board_topic.board, @board_topic)
      return
    end
    @posts = @board_topic.board_topic_posts
  end

  private

  def notify_on_post_update(post)
    BoardTopicNotificationsChannel.broadcast_to(
        post.board_topic,
        { event: 'post_updated', query_path: board_topic_posts_list_path(post.board_topic)}
    )
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.where(board: nil)
  end

  def show
    @board = Board.find(params[:id])
    if @board.to_param != params[:id]
      redirect_to boards_show_path @board
      return
    end
    @is_main_category = !@board.board
    @topics = @board.board_topics
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /user/new
  def new
    @user = User.new
  end

  # POST /user/new
  def create
    @user = User.new(
        username: params[:user][:username],
        email: params[:user][:email],
        password: params[:user][:password],
        password_confirmation: params[:user][:password_confirmation]
    )
    if @user.save
      set_login_cookie @user
      @user = User.new
      flash.now[:success] = 'Successfully saved!'
    else
      flash.now[:error] = @user.errors.full_messages.to_sentence
    end
    render :new
  end

  # POST /user/logout
  def logout
    authorize User
    cookies.delete :forum_account
    redirect_to root_path
  end

  # GET /user/login
  def login
    authorize User
    @user = User.new
  end

  # POST /user/login
  def login_perform
    authorize User
    @user = User.find_by username: params[:user][:username]
    if @user.try :authenticate, params[:user][:password]
      set_login_cookie @user
      User.current = @user
      flash.now[:success] = 'Login successful!'
    else
      flash.now[:error] = 'Login unsuccessful!'
    end
    render :login
  end

  private

  def set_login_cookie(user)
    cookies.encrypted.permanent[:forum_account] = {
        value: JSON.generate({
                                 user_id: user.id,
                                 lifetime: 7.days.from_now
                             }),
        secure: Rails.env.production?
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/board_topic_posts/_show.html.erb
<fieldset>
  <legend><%= post.username %></legend>
  <%= post.content %>
  <% if post.file.attached? %>
    <%= link_to "Download Attachment (#{post.file.filename}, #{Filesize.from("#{post.file.byte_size} B").pretty})", rails_blob_path(post.file) %>
    <% if policy(post).delete_file? %>
      <%= link_to "Delete File", board_topic_posts_delete_file_path(post), method: :delete %>
    <% end %>
  <% end %>
  <% if policy(post).delete? %>
    <%= link_to "Delete Post", board_topic_posts_delete_path(post), method: :delete %>
  <% end %>
  <hr/>
  <%= l post.created_at %>
</fieldset>

app/views/board_topic_posts/list.html.erb
<% @posts.each do |post| %>
  <%= render partial: 'show', locals: { post: post} %>
<% end %>

app/views/board_topics/new.html.erb
<%= form_for @board_topic, url: board_topics_create_path, remote: false do |f| %>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  <%= f.fields_for @board_topic_post do |p| %>
    <p>
      <%= p.label :content %>
      <%= p.text_area :content %>
    </p>
  <% end %>
  <%= f.submit 'Abschicken' %>
<% end %>

app/views/board_topics/show.html.erb
<div id="board-topic-id" data-id="<%= @board_topic.id %>" style="display: none;"></div>

Titel: <%= @board_topic.title %>

<div id="posts-list">
<% @posts.each do |post| %>
  <%= render partial: 'board_topic_posts/show', locals: { post: post} %>
<% end %>
</div>

<% if policy(BoardTopicPost).new? %>
  <%= form_for @board_topic_post_answer, url: board_topic_post_comment_path do |comment| %>
    <%= comment.label :content %>
    <%= comment.text_area :content %>

    <%= comment.file_field :file %>

    <%= comment.submit 'Abschicken' %>
  <% end %>
<% end %>

app/views/boards/index.html.erb
<% @boards.each do |board| %>
  <fieldset>
    <legend><%= link_to board.name, boards_show_path(board) %></legend>
    <% if board.boards.present? %>
      <% board.boards.each do |sub_board| %>
        <%= link_to sub_board.name, boards_show_path(sub_board) %><br /> <br />
      <% end %>
    <% else %>
      leer
    <% end %>
  </fieldset>
<% end %>

app/views/boards/show.html.erb
<p>Name: <%= @board.name %></p>


<% if @is_main_category %>
  <fieldset>
    <legend>Subboards</legend>
    <ul>
      <% @board.boards.each do |sub_board| %>
        <li><%= link_to sub_board.name, boards_show_path(sub_board) %></li>
    <% end %>
    </ul>
  </fieldset>
<% end %>

<hr />

<% if policy(BoardTopic).new? %>
  <%= link_to 'Neues Topic Erstellen', board_topics_new_path %>
<% end %>

<table style="border: 1px solid black;">
  <% @topics.each do |topic| %>
    <tr>
      <td><%= link_to topic.title, board_topics_show_path(@board, topic) %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if User.current %>
    <p>Eingeloggt: <%= User.current.username %><%= link_to 'logout', users_logout_path, method: :post %></p>
    <% else %>
    <p>Eingeloggt als Gast! Einloggen? <%= link_to 'login', users_login_path %></p>
    <% end %>
    <% if flash[:error] %>
      <fieldset><%= flash[:error] %></fieldset>
    <% end %>
    <% if flash[:success] %>
      <fieldset><%= flash[:success] %></fieldset>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/login.html.erb
<%= form_for @user, url: users_login_path, remote: false do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.password_field :password, required: true %>
  <%= f.submit 'Abschicken' %>
<% end %>

app/views/users/new.html.erb
<%= form_for @user, url: users_create_path, remote: false do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password, required: true %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, required: true %>
  <%= f.submit 'Abschicken' %>
<% end %>